version: "3.1"

services:
  shell:
    build: .
    image: thomet/docker-remote-dev:latest
    environment:
      - SSH_AUTH_SOCK=/home/developer/ssh-auth.sock
    volumes:
      - ${DOCKER_SOCK:-/run/host-services/docker.proxy.sock}:/var/run/docker.sock
      - ${DOCKER_SSH_SOCK:-/run/host-services/ssh-auth.sock}:/var/run/ssh-auth.sock
      - ~/.gitconfig:/etc/gitconfig
      - ~/.gnupg/:/home/developer/.gnupg/
      - ./dotfiles:/home/developer/.dotfiles:rw

